### ISSUE TITLE
Add a feed to a group

### ISSUE THREAD

**Issue by vaz-ar** [passiomatic/coldsweat#80]
I just started using coldsweat, and I noticed in the issues (specifically issue  #41) that we should be able to add a feed to a specific group when adding the feed.
If I have not imported an opml that contains groups, this is what the add feed pop up looks like : 
![add_feed](https://cloud.githubusercontent.com/assets/3344540/6315276/8df75334-b9fd-11e4-86c6-27d923e3fe6d.png)
If I have previously imported an opml file then I can choose an existing group for my feed, but not add a new group.  

Isn't there a way to add groups directly via the interface ?

**Comment by passiomatic** [comment]
> Isn't there a way to add groups directly via the interface ?

Unfortunately it is not possible. This is partly because my personal aversion to groups/categories/tags :) I have something like 60 feeds in the single default group - I just don't care to categorize the feeds I follow.

Writing a managing groups UI  is not a trivial task, so at least for now I decided not to pursue that path.

**Comment by vaz-ar** [comment]
Ok thanks for the response !
